dataset: ehrsql
db_id: mimic_iii
train_data_path : dataset/ehrsql/mimic_iii/train.json
valid_data_path : dataset/ehrsql/mimic_iii/valid.json

exp_name : ehrsql_mimic3_t5_base
mode: train
load_model_path: 
train_batch_size: 4
accumulation_steps: 8
eval_batch_size: 8

tables_path: 
add_schema: false
shuffle_schema: false

# use_wandb: true
# wandb_project: ehr-semantic-parsing
